version: '3'
services:
  db:
    image: 'mysql:5.7'
    ports:
      - '13306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: development
      MYSQL_USER: test-user
      MYSQL_PASSWORD: test-password

